config/routes.rb
GeoAdTest::Application.routes.draw do
  resources :users
 resources :sessions, only: [:new, :create, :destroy]


  root to: 'static_pages#home'


  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete


	match '/home',    to: 'static_pages#home'
	match '/help',    to: 'static_pages#help'
	match '/about',   to: 'static_pages#about'
	match '/contact', to: 'static_pages#contact'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }

	before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

    #private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new
  render 'new'
  end

	def create
		user = User.find_by_email(params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
		 # Sign the user in and redirect to the user's show page.
			 sign_in user
			redirect_to user
		else
		 # Create an error message and re-render the signin form.
		  flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
		end
	end



  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
  	 @user = User.new
  end

	def create

    @user = User.new(params[:user])
    if @user.save
    flash[:success] = "Welcome to the new world"
      redirect_to @user

    else
      render 'new'
    end

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
  	!current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

	  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to ".geoaddress", home_path, id: "logo" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help",   help_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_mohsHead.html.erb
   <head>
       <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <script type="text/javascript"
      src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBAzXHmOZDia5qwGZpWi3PF_rDLjTR1cXs&sensor=true">
    </script>
    <script type="text/javascript">
      function initialize() {
        var myOptions = {
          zoom: 12,
          center: new google.maps.LatLng(45.539212,-73.634708),
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById('map_canvas'),
            myOptions);

        google.maps.event.addListener(map, 'click', function(e) {
          placeMarker(e.latLng, map);
        });
      }

      function placeMarker(position, map) {
        var marker = new google.maps.Marker({
          position: position,
          map: map
        });

        map.panTo(position);

        marker.setTitle("lat="+marker.getPosition().lat().toFixed(5)+"; Long="+marker.getPosition().lng().toFixed(5));
        attachMessage(marker, map);
      }

    function attachMessage(marker, map) {
        var infowindow = new google.maps.InfoWindow(
            { content: "Compagnie ABC "+" lat="+marker.getPosition().lat().toFixed(5)+"; Long="+marker.getPosition().lng().toFixed(5)
            });
        google.maps.event.addListener(marker, 'click', function() {
            infowindow.open(map,marker);
        });
    }

      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
  </head>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

	<%= render 'layouts/mohsHead' %>


  <body onload="initialize()">






    <%= render 'layouts/header' %>
    <div class="container" style="width=100%; height=600px">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
		<%= render 'layouts/footer' %>
		 <%= debug(params) if Rails.env.development? %>
    </div>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>


<table border="0" width="100%">
	<tr>
		<th><%= link_to image_tag("link22.jpg", alt: "Geodesic"), home_path %></th>
		<th>

			<h1>Contact Us</h1>
			<p>{Notre GéoAddresse} </p>
			<p>514 777 9999 </p>
			<p>Montréal </p>
		</th>
	</tr>
</table>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>


<table border="0" width="100%">
	<tr>
		<th><%= link_to image_tag("sgrid4.gif", alt: "Geodesic"), home_path %></th>
		<th>

			<h1>Addresses, gone global</h1>
			<p>GeoAddress is a tool for the world to communicate addresses and geo-informations </p>
		</th>
	</tr>
</table>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>


<div id="map_canvas" style="width:100%; height:500px; margin-bottom:2em"></div>


<div id="explications" text-align="left" width="80%">
	<h2>À Faire</h2>
	<p>
		<ul>
		  <li>Faire le template des informations</li>
		  <li>Élargir l'inputText</li>
		  <li>Revoir la grandeur des caractères</li>
		  <li>Moh1 : J'ai inclus ton code, mais pas selon les bonnes pratiques de rails. J'ai trouvé un gem qui pourrait faire l'affaire : http://railscasts.com/episodes/273-geocoder' '</li>
		  <li>Moh2 : Je suis en train d'apprendre comment utiliser les db. Je suis rendu à la section 6 (création d'utilisateurs avec la DB etc.) du tutorial - qui est d'ailleurs vraiment EXCELLENT.</li>

		</ul>
	</p>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>